name: amplitude_flutter
description: Official Flutter plugin for tracking events and revenue to Amplitude.
version: 1.4.5
homepage: https://github.com/amplitude/Amplitude-Flutter

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  crypto: ^3.0.1
  device_info_plus: ^11.2.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.5.0
  objectbox: ^5.0.0
  objectbox_flutter_libs: ^5.0.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  uuid: ^4.5.1
dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  objectbox_generator: any

flutter:
  plugin:
    platforms:
      android:
        package: com.amplitude.amplitude_flutter
        pluginClass: AmplitudeFlutterPlugin
      ios:
        pluginClass: AmplitudeFlutterPlugin
